apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: klongpy
spec:
  capacity:
    storage: 20Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.0.10
    path: "/volume1/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: klongpy
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Ti
