apiVersion: apps/v1
kind: Deployment
metadata:
  name: klongpy-app-deployment
  namespace: klongpy-feed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: klongpy-app
  template:
    metadata:
      labels:
        app: klongpy-app
    spec:
      containers:
      - name: klongpy-app
        image: klongpy-app:latest
        ports:
        - containerPort: 8000
        env:
        - name: KG_FILE_PATH
          value: "/data/hello.kg" # Set the path to the .kg file
        volumeMounts:
        - name: nfs-volume
          mountPath: /data
        resources:
          limits:
            cpu: "1"
            memory: "8Gi"
          requests:
            cpu: "0.5"
            memory: "1Gi"
      volumes:
      - name: nfs-volume
        persistentVolumeClaim:
          claimName: klongpy-feed-pvc
