apiVersion: v1
kind: PersistentVolume
metadata:
  name: klongpy-feed-pv
spec:
  capacity:
    storage: 20Ti
  accessModes:
    - ReadWriteMany
  claimRef:
    name: klongpy-feed-pvc
    namespace: klongpy-feed
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs:
    server: 192.168.0.10
    path: "/volume1/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: klongpy-feed-pvc
  namespace: klongpy-feed
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Ti
