name: Build and Publish

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel==2.16.5 build
      - name: Build wheels
        run: |
          python -m build --sdist -o dist
          python -m cibuildwheel --output-dir dist
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: wheels-${{ matrix.os }}
          path: dist

  publish:
    needs: build_wheels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: dist
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        run: |
          python -m pip install --upgrade pip
          pip install twine
          twine upload dist/**/klongpy-*.whl dist/**/klongpy-*.tar.gz
