name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:

  linter:
    name: Linter
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint flake8
        pip install -e ".[full,torch]" --extra-index-url https://download.pytorch.org/whl/cpu
#     - name: Lint with pylint
#       run: python -m pylint --disable=all -e W0311 --jobs=0 --indent-string='  ' **/*.py
    - name: Lint with flake8
      run: flake8 klongpy/ --indent-size=2 --select=F,E112,E113,E304,E502,E702,E703,E71,E72,W191,W6,W605 --ignore=E731,W605,F405,F403 --statistics -j4
#     - name: Lint klongpy with pylint
#       run: pylint klongpy/

  testcpu:
    name: CPU Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Update packages
      run: sudo apt-get update
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install -e ".[full,torch]" --extra-index-url https://download.pytorch.org/whl/cpu
    - name: Run unittest
      run: python3 -m unittest -v
